spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/databank
    username: root
    password: mysql
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true